### ISSUE TITLE
добавить описание команд

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#1]
Добавить в файл README.md описание команд:
1. клонирования репозитория,
2. установки зависимостей,
3. запуска скриптов сборки во всех доступных режимах, запуска сервера.

([стандарты. инициация. п1](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78iac/))

Таким образом любой проверяющий должен видеть описание команд в файле описания проекта, а не выискивать их по кишкам разных файлов.
До кучи - npm i не работает, ругается на имя пакета 
![image](https://user-images.githubusercontent.com/33621369/57995645-6b724700-7aed-11e9-92b4-c15ea846947f.png)

**Comment by arkhannanov** [comment]
Обновил описание. Добавил необходимую информацию.

Кстати, npm i у меня работает.

https://github.com/arkhannanov/FSD_CV/blob/master/README.md
