### ISSUE TITLE
Пути подключаемых файлов

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#11]
Проверь пути подключаемых файлов в блоках. npm run dev ругается

**Comment by arkhannanov** [comment]
Склонировал проект в тестовую папку, затем запустил npm i. Далее проверил запуск npm run dev, все грузится, все работает. У тебя не так?

**Comment by Frolikow** [comment]
в рамках [этого комита](https://github.com/arkhannanov/FSD_CV/commit/183bfc6b8dd54a1de074dc0aa75ab420beb41a7b) было исправлено.
Вчера `npm run dev` ругался на не правильные пути модулей
