### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#12]
Относись к Pug-коду как к js-коду. Делай переносы  на слишком больших строках, не пропускай пробелы где они важны
Например здесь после знаков `=` нужны пробелы
![image](https://user-images.githubusercontent.com/25764783/58372234-f1a2e900-7f44-11e9-9017-67245b6e0c10.png)
И аргументы миксинов тоже разделяй пробелами, код будет легче читаться

А здесь явно перебор с длиной строки
https://github.com/arkhannanov/FSD_CV/blob/e97222a5e58be9d5eeba17760c24ebd70d6d6b71/src/blocks/block_profile/profile.pug#L7

**Comment by arkhannanov** [comment]
Сделано.

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/58391087-7d5c6880-805e-11e9-8a4b-2a4a53eaadff.png)
При вызове миксина, где аргументы разделяешь пробелом, где-то нет. 

В таких местах вообще боль
![image](https://user-images.githubusercontent.com/25764783/58391134-a977e980-805e-11e9-9b02-25789231c6f7.png)
но тут лучше не отступ, а переносы добавить.

**Comment by arkhannanov** [comment]
Сделано. Теперь аргументы разделены пробелами, добавлены переносы на новую строку.

**Comment by Frolikow** [comment]
у тебя получилось так
```pug
.experience__item
            include ../experience-item/experience-item.pug
            +experience-item("COMPANY NAME", 
            "// Feb 2011 - Jun 2014","YOUR JOB HERE", 
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque.")
            +experience-item("COMPANY NAME", 
            "// Feb 2011 - Jun 2014","YOUR JOB HERE", 
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque.")
            +experience-item("COMPANY NAME", 
            "// Feb 2011 - Jun 2014","YOUR JOB HERE", 
            "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque.")
```
что здесь не то? если разбиваются аргументы посторочно, то это делается для **каждого** аргумента. Если аргумент слишком длинный, как у тебя, его тоже разбивай на строки.
Пример:
```pug
+experience-item(
    "COMPANY NAME", 
    "// Feb 2011 - Jun 2014",
    "YOUR JOB HERE", 
    "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. 
        Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        Donec quam felis, ultricies nec, pellentesque."
)
```

**Comment by arkhannanov** [comment]
Привет. Да, разбил для каждого аргумента. Во втором случае, в случае длинного аргумента не получается разбить на строки, проект не собирается. Тоже хотел разбить.

В случае как тег например с контентом большим p можно разделить на строки, тут не получается.

p
 | Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст
 | Текст Текст Текст Текст Текст Текст Текст Текст Текст Текст

**Comment by Frolikow** [comment]
если вместо одинарных или двойных кавычек использовать обратные кавычки, то можно спокойно бить на строки как тебе нравиться

еще замечание актуальное. при работе на ишью делай так:
1) прочитал ишью, понял задачу
2) сделал задачу именно текущего ишью, 
3) закомитил с соотвтствующим номер (например `#12 refactoring`)
4) на следующей задаче заново)

иначе получается что ты правки делаешь а комитишь их в другое ишью, и искать твои правки - не самое увлекательное занятие))

**Comment by arkhannanov** [comment]
Забавно) Не знал об этом, о силе обратных кавычек. Исправлено.

**Comment by Frolikow** [comment]
Не забывай делать Pug-файлы читабельнее.
вместо подобных вещей
```pug
+experience({source: "./img/experience-icon.png", 
title: "experience", 
companyname: "company name", 
date: "// Feb 2011 - Jun 2014", 
job: "Your job here", 
text: `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et 
magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, 
ultricies nec, pellentesque.`})
```

лучше писать:
```pug
+experience({
    source: "./img/experience-icon.png", 
    title: "experience", 
    companyname: "company name", 
    date: "// Feb 2011 - Jun 2014", 
    job: "Your job here", 
    text: `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
        Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et 
        magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, 
        ultricies nec, pellentesque.`
})
```

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Frolikow** [comment]
Посмотри еще раз, внимательно на мой пример, аргументы которые ты передаешь в миксин, не должны быть на одном уровне с вызовом миксина. Делай для них отступ(это и js касается). скобка закрывающая у оператора вызова, должна находиться на одном уровне с открывающей скобкой.

**Comment by arkhannanov** [comment]
Ага, исправил.

**Comment by Frolikow** [comment]
Вот теперь на pug-файлы смотреть приятно)
