### ISSUE TITLE
Выложить макет для perfectpixel

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#14]
Выложи макет (в смысле картинку), которую использовал для perfectpixel и настройки его. Можно положить в корень проекта и залить.

**Comment by arkhannanov** [comment]
На самом деле особо не придерживался pixelperfect, видимо зря) Сейчас все подгоняю под оригинальный дизайн. Скоро выкачу.

**Comment by arkhannanov** [comment]
Привет! 

Готов. Макет в корне cv.jpg. Настроек никаких нет.

Вот так они выглядят, нулевые http://prntscr.com/nuy1g4
