### ISSUE TITLE
Избавиться от хардкода

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#15]
Объясни структуру этих строк(хотя бы 1). Что ты в них делаешь?
```pug
-let {source="./img/phone-icon.png", title, address , email , phone, website} = options;
-let {name= "name", surname= "surname", title= "graphic designer"} = options;
-let {source= "./img/education-icon.png", title= "education", degree= "master degree", date= "// Feb 2011 - Jun 2014", universityname= "university name", text= "text"} = options;
и т.п....
```

**Comment by arkhannanov** [comment]
Делаю так, чтобы название переменных было например не options.name, а просто name. Просто взял рекомендацию Сергея. См ишью #2.

**Comment by Frolikow** [comment]
Ладно, понятно, дефолтные значения это хорошо.
Но тогда, например блок contact, поясни теперь вот эту строку
```pug
mixin contact(options = {source: "./img/phone-icon.png", title: "contact", address: "Main Street, City.", email: "contact@domain.com.", phone: "555-555-555", website: "www.yourweb.com"})
```

учитывая что следом за ней идет 
```pug
-let {source="./img/phone-icon.png", title="contact", address ="Main Street, City.", email= "contact@domain.com.", phone= "555-555-555", website= "www.yourweb.com"} = options;
```
 тут явно что-то лишнее))

**Comment by arkhannanov** [comment]
То есть сделать так? Правильно ли я понял? То есть убрать первичные значения объекта?

[mixin contact(options = {source: "", title: "", address: "", email: "", phone: "", website: ""})
    -let {source="./img/phone-icon.png", title="contact", address ="Main Street, City.", email= "contact@domain.com.", phone= "555-555-555", website= "www.yourweb.com"} = options;](url)

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Frolikow** [comment]
Блок `contact`
Ты в него передаешь все данные, зачем эти же данные внутри хардкодить? что произойдет когда в миксин передам какой-то другой, например, сайт?

Блоки `experience` и `education`
Представим что данные в этих блоках одинаковые(в своих блоках) по случайности. Что произойдет когда я вызову миксин `+education` и передам в него данные о трех _разных_ местах учебы? Нужно продумать эти моменты.

**Comment by arkhannanov** [comment]
1. Исправлено.
2. В данном случае было заточено на то что в блоках experience и education может быть 100 позиций. Если нужно переписать для 3-х разных - могу сделать. Отпишись.

Спасибо!

**Comment by Frolikow** [comment]
1. Лучше использовать шаблонные строки, вместо конкатенации.
2. Хорошо если заточено аж 100) но я мб не точно выразился, представь что в текущей реализации, нужно передать в миксин` +education` сколько-то позиций( **разных**). Как твоя реализация сейчас это воспримет и что выведет в документ миксин?

**Comment by arkhannanov** [comment]
1. Готово.
2. Реализовать через массив объектов? Это имеется ввиду? А реализацию реализовать через цикл по массиву объектов? Верно?

**Comment by arkhannanov** [comment]
Кстати, я проверил через шаблонные строки не добавился e-mail, а с конкатенацией добавился. В чем ошибка? Может оставить как было?

С обратными кавычками тоже не работает.

**Comment by arkhannanov** [comment]
Отбой) С обратными кавычками сработало, разобрался)

**Comment by Frolikow** [comment]
> Кстати, я проверил через шаблонные строки не добавился e-mail, а с конкатенацией добавился. В чем ошибка? Может оставить как было?
> 
> С обратными кавычками тоже не работает.

А попробуй использовать шаблонную строку внутри обратных кавычек;))

> Реализовать через массив объектов? Это имеется ввиду? А реализацию реализовать через цикл по массиву объектов? Верно?

Да, верно

**Comment by arkhannanov** [comment]
1. Пишу вот так 

`a(href=`mailto: ${email}`, class="contact__item__container-content")= email `

Так не работает...(

2. Скоро выкачу.

**Comment by arkhannanov** [comment]
1. Жду  ответа.
2. Готово.

**Comment by Frolikow** [comment]
видимо, в рамках другого ишью реализовал. Будь внимательнее. 

upd. это про ссылки я, если что

**Comment by Frolikow** [comment]
По поводу блоков со списками, опять вопросы.
Если я захочу передать 3 элемента в миксин? выдает ошибку
Если я захочу передать 5 элементов в миксин? последний игнорируется
почему так?

**Comment by arkhannanov** [comment]
Но если перейти по maito:  ${email} в адрес письма забивается ${email}, а не переданный параметр contact@domain.com.

Вот и спрашиваю, может оставить конкатенацию?

**Comment by arkhannanov** [comment]
Не понимаю в чем косяк. Если реально смотреть на задачу, то зачем передавать 3 миксина вместо 4-х или 5-ть вместо 4-х.

Может быть текущая реализация смотрится как костыль, может быть. Тогда как сделать ее адаптивной? Перед глазами у меня нет лучших практик.

Еще в рамках текущего ишью хотел бы спросить как сделать декомпозицию для массива объектов, то есть передавать не options.headline.source, а просто source как аргумент вложенного миксина?

Я пробовал сделать, но у меня ошибки. Поэтому передаю полностью элементы объекта через точки.

Спасибо.

**Comment by Frolikow** [comment]
> Но если перейти по maito: ${email} в адрес письма забивается ${email}, а не переданный параметр [contact@domain.com](mailto:contact@domain.com).
> 
> Вот и спрашиваю, может оставить конкатенацию?

как сейчас у тебя сделано - у меня работает исправно. только графу с телефоном поправь, два раза номер передаешь

**Comment by arkhannanov** [comment]
Исправлено. C шаблонными строками выходит закончили)

**Comment by Frolikow** [comment]
> Еще в рамках текущего ишью хотел бы спросить как сделать декомпозицию для массива объектов, то есть передавать не options.headline.source, а просто source как аргумент вложенного миксина?
> Я пробовал сделать, но у меня ошибки. Поэтому передаю полностью элементы объекта через точки.

```pug
mixin education(options ={headline: {source: "", title: ""}, content:[{degree: "", date: "", universityname: "", text: ""}, {degree: "", date: "", universityname: "", text: ""}, {degree: "", date: "", universityname: "", text: ""}, {degree: "", date: "", universityname: "", text: ""}]})
    -let {headline:{source,title}, content} = options
```
Понятно что сделал?
_________________
> Не понимаю в чем косяк. Если реально смотреть на задачу, то зачем передавать 3 миксина вместо 4-х или 5-ть вместо 4-х.
> Может быть текущая реализация смотрится как костыль, может быть. Тогда как сделать ее адаптивной? Перед глазами у меня нет лучших практик.

```pug
.education__item
    each item in content
        -let {degree, date, universityname, text} = item
        +education-item(degree, date, universityname, text)
```
понимаешь?

**Comment by arkhannanov** [comment]
Вау, супер!) Теперь на примере более понятно, совсем не очевидно с первого раза.

Понимаю, только не совсем понятно, почему -let {degree, date, universityname, text} = item идет после конструкции each item in content, item то не определено пока что.

И второе, при описании миксина, в optios в массив content передавать фиксированное, заранее определенное количество элементов или нет? Просто боюсь если передать 3, то будет ошибка, а 5-ть опять не определится.

**Comment by arkhannanov** [comment]
Уточнение.

Кажется понял, при описании миксина вообще можно массив с именем content передать пустой. Верно?

Только вот:
each item in content
        -let {degree, date, universityname, text} = item

Не совсем понятно почему item в конструкции each item in content нигде ранее не определяется?

**Comment by arkhannanov** [comment]
Ой, что-то я туплю) Метод each итак идет по элементам массива. Теперь все понятно)

**Comment by Frolikow** [comment]
item определяется внутри each...in , т.е. на каждой итерации item будет равен элементу массива соответствующего текущей итерации.

При использовании  each...in, ты можешь передать массив вообще любой длины, т.к. цикл не подразумевает никаких условий и просто проходит по каждому элементу(даже если их 0).

Все ясно?)

**Comment by arkhannanov** [comment]
Да, все понятно. Спасибо! Скоро выкачу.

**Comment by arkhannanov** [comment]
Сделано в рамках ишью #2
