### ISSUE TITLE
Не дублировать имя блока в CSS

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#16]
не надо писать заново имя блока, в sass можно на верхние селекторы ссылаться.

**Comment by arkhannanov** [comment]
Не понял немного, это где? Без примера не понял. Напиши, плиз.

**Comment by Frolikow** [comment]
Это касается всего проекта. Можешь прочитать в доках, как раз с примерами https://sass-scss.ru/documentation/rasshirenie_css/ssilka_na_roditelya_selektora/

**Comment by arkhannanov** [comment]
Да, я знаю это правило. Но где он применимо в этом первом проекте? Или я где-то невнимательно смотрю? Вроде дублей нет.

Покажи, пожалуйста, именно в моем коде где можно имя родительского блока заменить на &.

Спасибо!

**Comment by arkhannanov** [comment]
Готово.

**Comment by Frolikow** [comment]
А например в  [этом файле](https://github.com/arkhannanov/FSD_CV/blob/master/src/blocks/experience-item/experience-item.scss) почему не сделал?

**Comment by arkhannanov** [comment]
Посмотри сначала, сначала сделал. А дальше просто идет вложенный блок, и есть обращаться через &, то уже будет не .experience-item, а  .experience-item__dot-container

**Comment by Frolikow** [comment]
А там точно нужна вложенность? без нее нельзя это решить?

**Comment by arkhannanov** [comment]
Думал, что вложенность обязательно нужна... Выходит только кавычки определяют порядок. Ок. Правлю...

Мне просто казалось, что это не совсем правильно.

**Comment by Frolikow** [comment]
у тебя в контексте одного блока, все элементы разные) если есть одноименные элементы в разных элементах, тогда вложенность будет необходима)

**Comment by arkhannanov** [comment]
Перепроверил. Для вложенных блоков не получается поставить &, если даже переносить на тот же вертикальный уровень.

Поставил где была возможность &.

Сорри, что в этом коммите есть немного лишнего. Просто обнаружилась ошибка, ее исправлял, она попала в этот коммит. Стараюсь не миксовать коммиты.

**Comment by Frolikow** [comment]
Ради интереса попробовал сделать то что я прошу, все работает без проблем.
Амперсанд ставится везде. И стили все браузером воспринимаются.
Видимо ты где-то ошибку делаешь при выполнении

**Comment by arkhannanov** [comment]
Для примера давай возьмем этот маленький блок (сейчас так):

.education-item {   
  margin-top: 2.083rem;
  margin-bottom: -0.625rem;
  display: flex;
  flex-direction:row;
  margin-left: -0.08rem;

  &__dot-container {
    margin-right: 5%;
    margin-top: 0.5%;
    align-self: flex-start;

    .education-item__dot {
      background: $mainFontColor;
      height: 1.285rem;
      width: 1.285rem;
      border-radius: 50%;
      margin-top: -0.07rem;
      margin-left: 0.9rem;
      @media screen and (max-width: $desktopWidth) {
        height: 1rem;
        width: 1rem;
      }
      @media screen and (max-width: $tableWidth) {
        height: 0.833rem;
        width: 0.833rem;
      }          
    }
  }
_______________________________________________________________
Если сделать так, то стили не определяются:

.education-item {   
  margin-top: 2.083rem;
  margin-bottom: -0.625rem;
  display: flex;
  flex-direction:row;
  margin-left: -0.08rem;

  &__dot-container {
    margin-right: 5%;
    margin-top: 0.5%;
    align-self: flex-start;

  &__dot {
      background: $mainFontColor;
      height: 1.285rem;
      width: 1.285rem;
      border-radius: 50%;
      margin-top: -0.07rem;
      margin-left: 0.9rem;
      @media screen and (max-width: $desktopWidth) {
        height: 1rem;
        width: 1rem;
      }
      @media screen and (max-width: $tableWidth) {
        height: 0.833rem;
        width: 0.833rem;
      }          
    }
  }
_________________________________________________________________________________

Или я что-то неправильно понял?

**Comment by Frolikow** [comment]
> Или я что-то неправильно понял?

Увы, да)Про смысл фигурных скобок говорить излишне?))

**Comment by arkhannanov** [comment]
Так где ошибка то, скажи, пожалуйста, вообще рефакторинг первого проекта идет уже 2 недели. Не много ли для такого маленького проекта? И вообще было бы неплохо не просто стандарты видеть, а примеры реально рабочего кода, ведь увидев раз - просто берешь это за основу. Вначале у меня не было примеров реального кода, который подходит под стандарты FSD.

Даст бог закончу этот этап опишу в комментариях что было бы хорошо иметь перед глазами реальные примеры.

Так все же? Что не так?

Вообще я изначально понимал что предпроцессор помогает сокращать код CSS. То есть путем вложенности стилей друг в друга можно сразу описывать стили дочерних элементов. Фигурные скобки показывают границы элементов.

Я что-то не так понял?

**Comment by Frolikow** [comment]
Тот пример который ты скинул, имеет открывающиеся скобки на каждом блоке правил, а закрывающиеся пачкой в конце. 
Блок стилей обрамляешь в скобки. Ты ведь пытаешься убрать вложенность, а скобки какраз говорят кто куда вложен.

**Comment by arkhannanov** [comment]
Так делать - стандартная практика, так всегда теперь делать? Немного непривычно просто...

И вообще нужно ли это сокращение, если все равно стили из html/pug файла вставляешь как есть?

Или красота требует жертв?

Или идея заключается чтобы описать все БЭМ элементы в рамках одного блока?

Просто мне показался удобным мой подход при классическом объявлении стилей... Согласен, наверно при компонентном подходе вариант с & уместнее.

Спасибо.

**Comment by Frolikow** [comment]
Дублирование имени блока в стилях - это плохая практика. При компонентной верстке, у тебя, зайдя в стили, сразу понятно какой блок стилизуется, т.к. по факту он один раз написан, и все остальное через амперсанд записываешь. Единственный минус - это если у тебя в соседних одноименных элементах, лежат другие одноименные элементы, которым надо персональные стили. Тогда решается вложенностью, или изменением имен элементов.

А вообще в sass не увидел(что странно) , но например stylus'e есть оочень удобные вещи для ссылки на блок. Например не зависимо от вложенности ты можешь написать ^[0]__elementName, и стили будут читаться как blockName__elementName. 

> Или идея заключается чтобы описать все БЭМ элементы в рамках одного блока?

это одна из основных идей БЭМа и компонентной верстки в целом, блок должен быть полностью независим, включая свои стили

**Comment by arkhannanov** [comment]
Хорошо, понял. Готово)
