### ISSUE TITLE
include'ы

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#18]
все подключения файлов в pug'е , вроде этого:
```pug
include ../education/education.pug
```
лучше делать в начале файлов, например так: 
![image](https://user-images.githubusercontent.com/25764783/58777059-a8aefc80-85f6-11e9-8029-c6d22d3bd74d.png)

**Comment by arkhannanov** [comment]
Готово)

**Comment by Frolikow** [comment]
При исправлении ишью, если я явно не пишу что нужно` во всем проекте править`, нужно проверять весь проект, тем более из описания задачи мне кажется это очевидным. 
В случаях когда какое-то конкретное место нуждается в решении я пишу конкретно про это место) 

А получается:
1) я пишу тебе задачу(не конкретную), 
2)ты выполняешь ее в одном месте, 
3)я проверяю
но весь остальной проект покрыт такими же ошибками, 
1) я опять пишу про те же самые  ошибки,
2)ты заново  исправляешь
3) я заново проверяю

Ты ведь знаешь свой проект лучше, и при повторяющейся ошибке - ты ее за один проход можешь сделать. И в результате на выполнение ишью как минимум в 2 раза меньше времени будет тратиться.

В других ишью я буду ссылаться на это сообщение, когда будет необходимость)

По поводу текущей задачи - поправь плиз во всем проекте)

**Comment by arkhannanov** [comment]
Ок. Хорошо. Наверное подразумевалось еще заголовки в миксинах вынести наверх, верно?
В index.pug включаю миксин уже в body, так?

**Comment by arkhannanov** [comment]
Хотел исправить неверный коммит ввел git commit --amend. Что-то не получилось. Выпало меню, а как дальше - не понял.

**Comment by Frolikow** [comment]
> Ок. Хорошо. Наверное подразумевалось еще заголовки в миксинах вынести наверх, верно?
> В index.pug включаю миксин уже в body, так?

подразумевалось - дословно:
> все подключения файлов в pug'е

так что, проверяй еще, где пропустил)

по поводу ` git commit --amend` не подскажу, т.к. ни разу не юзал его

**Comment by arkhannanov** [comment]
Получается готово по этому ишью. Теперь все основные pug файлы подключаются в блоке page.

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/58813971-1129c800-864f-11e9-9fd9-a104ef6d6c46.png)
![image](https://user-images.githubusercontent.com/25764783/58813985-15ee7c00-864f-11e9-9e15-01b5e7a6fc05.png)
Внимательнее

**Comment by arkhannanov** [comment]
Теперь наверное точно все)
