### ISSUE TITLE
Блоки переписать на миксины

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#2]
Блоки по БЭМ должны быть реализованы миксинами. Параметры блоков должны передаваться объектами - в корневом блоке задаваться все параметры, внутри распределятся по более мелким блокам. То есть у проекта должна быть древовидная структура. Это требование компонентности верстки подобно подходу, применяемому в react. На риззоме есть требование по этому поводу во 2 задании и ссылка на статью.

**Comment by arkhannanov** [comment]
Блоки переписаны на миксины

**Comment by Sergio-Ka** [comment]
Миксины здесь нужны не просто так. У тебя никакие параметры не передаются кроме миксина avatar. То есть хотя у тебя и есть миксины, но по факту блоки статичны и чтобы изменить их содержание нужно каждый раз лезть в кишки блока и менять его непосредственно. Переделай так, чтобы параметры передавались сверху. Сразу скажу, что параметры нужно передавать не просто через запятую, а объектами (или массивом объектов), так как это дает ряд преимуществ, например необязательность того или иного параметра, возможность указать параметры по умолчанию. Внутри блоков использовать декомпозицию для того чтобы имя параметров было не например options.name, а просто name. Таким образом на примере блока avatar там где он вызывается это будет выглядеть так:
```
+avatar({name: "name here", surname: "surname", profession: "graphic designer"})
```
а там где создается миксин может выглядеть например так:
```
mixin avatar(options = {name:"name", surname:"surname", profession:"graphic designer"})
    -let {name="name", surname="surname", profession="graphic designer"} = options;
```
и так далее.

**Comment by Sergio-Ka** [comment]
Тут кстати еще в дополнение:
```
mixin education
    .education
        .education__headline
            include ../headline/headline.pug
            +headline("./img/education-icon.png", "education")
        .education__item
            include ../education-item/education-item.pug
            +education-item(`master degree`, 
            `// Feb 2011 - Jun 2014`,
            `university name`, 
            `Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
            Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque 
            penatibus et magnis dis parturient montes, nascetur ridiculus 
            mus. Donec quam felis, ultricies nec, pellentesque.`)
            +education-item(`master degree`, 
```
Такого типа реализация плохая. Тут надо передавать массив объектов с параметрами на вход миксина. И итерироваться в зависимости от количества переданных в массиве объектов и отрисовывать для каждого объекта свой пункт - так нужно делать потому, что пунктов в education может быть много, например 100 и все они могут быть разные и если тебе в одном лишь надо будет исправить какую-то мелочь - то можно будет зарыться. При такой реализации создавать миксин для education-item будет избыточным. Хотя если сильно хочется то можно. Кроме того тут можно заметить, что в целом эти внутренние пункты у education и experience схожи между собой и тут если уж создавать отдельный миксин для этого, то стоит вынести для них в один общий блок.

**Comment by arkhannanov** [comment]
Ага, понятно. Исправил все уже. Да, education и experience схожи, но стили у них немного отличаются. Так бы и сделал два, если бы они были идентичными. Сейчас запушу обновления.

**Comment by arkhannanov** [comment]
Готово. Единственное что - не понял как можно укорачивать строки при реализации миксина.

**Comment by Frolikow** [comment]
> параметры нужно передавать не просто через запятую, а объектами

Проверь внимательно весь проект

**Comment by arkhannanov** [comment]
Готово.

**Comment by Sergio-Ka** [comment]
>Да, education и experience схожи, но стили у них немного отличаются. Так бы и сделал два, если бы они были идентичными.

Какие глупости. Если у них немного различаются стили, то стандартный подход в бэм в таком случае не плодить сотни сущностей, а выделять базовую, а остальное переопределять/определять модификаторами. От сюда выйдет, что у тебя item одинаковые,а стало быть и блоки education/experience одинаковые, а то что у них разные имена  и содержимое - передаешь параметрами в виде объектов или массивов объектов. Хотя объективно у тебя тут скорее всего все же будут два разных блока education/experience так по смыслу и внешнему виду выходит, но это будут всего лишь обертки, возможно с внутренними элементами типа какого нибудь хидера и контейнера, а вот кишки их - по любому должно быть одним блоком который и в education инклюдится и вызывается в виде миксина и в experince.

**Comment by arkhannanov** [comment]
Хорошо. А как класс передать в миксине? 

Допустим у меня отличающийся блок имеет класс .education-item__degree-wrapper.

Как Pug'ом передать разные классы одному и тому же элементу?

**Comment by Sergio-Ka** [comment]
Я не понимаю твой вопрос. Класс передать так же как и все остальное - параметром. Если вопрос о том как потом использовать переданный строкой модификатор, то я например делал это так как-то:
.content-list__item-name(class= `content-list__item-name_color_${item.headerColor}`)= item.headerOfItem

**Comment by arkhannanov** [comment]
Ага, теперь ясно. Спасибо.

**Comment by Sergio-Ka** [comment]
Тут сейчас напишу оставшиеся в рамках этого вопроса проблемы:
1.  a(href=`mailto: ${email}`, class="contact__item-content")= email  эти вещи в блоке контакта нужно написать с использованием точечной нотации для классов, то есть типа a.contact__item-content(href=`mailto: ${email}`)= email
2. Здесь
```
.profile__text= text
            span.profile__text_bold= bold
```
сделано не корректно, у тебя модификатор .profile__text_bold висит в воздухе а должен быть на блоке или элементе. Если же ты его используешь вместе с указанием внешнего элемента, то тоже будет плохо. Выход: добавить еще элемент, например какой нибудь .profile__marked-text вместо модификатора.
3. Про блок skills  Егор тебе написал уже в каком-то из issue - нужно передавать массив объектов параметров и итерироваться по нему с помощью forEach без всякого хардкода типа while i < 4. Потому как у тебя только в этом проекте эти скилы одинаковые и число их задано, а по факту они могут быть разные и все это должно передаваться сверху через параметры. И такой же подход должен быть к блокам education experience и возможно education. И кстати var i = 0; var при объявлении переменных мы стараемся не использовать, это загрязняет глобальную область видимости, а вот такую запись i++; нужно писать в виде i+=1; в соответствии со стандартами fsd которые ссылаются на стандарты AirBnB.
4.В блоке software все плохо. Модификаторы .software__items_left-column висят в воздухе, а должны быть как я уже говорил на блоке или элементе. Кроме того они тут вообще не нужны по хорошему. Выстраивание твоих прогрессбаров можно сделать на CSS, а порядок их задавать в объектов с их параметрами. При таком подходе получиться лаконично и понятно и без хардкода. По блока вроде все замечания. Для примера тебе дам блок software который написан у меня, попробуй разобраться и сделать по аналогии этот блок и блоки education experience:
include ../header-of-block/header-of-block.pug
```
mixin software(options = [{software:"photoshop", level:"91.228"}])
    section.software
        +header-of-block("software")
        .software__content
            -options.forEach(function(item) {
                .software__item
                    .software__name= item.software
                    .software__scale
                        .software__scale.software__scale_filled(style= `width: ${item.level}%;`)
            -});
```

**Comment by arkhannanov** [comment]
Код понял. Только не понял как ты раскидал по левой и правой колонке...

Через флексы и flex-flow: column wrap? Так примерно?

Правда в таком случае нужно задавать высоту родительского элемента, а дочернего получается на 33%, чтобы было два столбца по три строчки...

Хотя можно наверное и так:

.parent {
  display: flex;
  align-items: flex-start;
  flex-wrap: wrap;
  height: 100%;
}
.child {
  width: 50%;
}

Тогда отчет слева направо пойдет и элементы будут распределяться по двум колонкам. Правильно я понимаю, так делал?

**Comment by arkhannanov** [comment]
1. Готово

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
3. Готово.

**Comment by arkhannanov** [comment]
4. Software готово. Не стал делать через стилизацию ширины блока CSS, ведь есть в HTML5 тег progress. Вроде даже короче получилось)

**Comment by arkhannanov** [comment]
Готовы также блоки experience и education. Единственное что - не получилось присвоить модификатор через шаблонные строки, просто не работает, сделал через канкатенацию.

**Comment by arkhannanov** [comment]
Кстати, исправил через шаблонные строки. С обратными кавычками получилось.

**Comment by Sergio-Ka** [comment]
1. Вместо такого:
```
let { headline, skills } = options;
let { source, title } = headline; 
```
нужно делать так:
```
-let { headline: { source, title }, skills } = options;
```
И это не только в skills
2. Это хардкод:
```
            - var i = 0;
            while i < 12
                if i < numberOfDots
                    .skills-filled-points_filled-point
                else
                    .skills-filled-points_empty-point
                - i++;
```
во-первых, максимальное количество пойнотов должно передаваться сверху через параметры, так как сейчас тут 12 пойнтов, а завтра дизайнер скажет тебе сделать 10, а послезавтра 8 и тебе каждый раз в кишки лазить придется. Во-вторых про var и i++ уже здесь писал.

3. В этом:
```
mixin software(options = {headline:{ source: "", title: "" }, skills: []})
    -let { headline, skills } = options;
    -let { source, title } = headline; 
    .software
        .software__headline
            +headline( source, title)
        .software__items
            each item in skills
                -let {skill, level} = item;
                +software-bar(skill, level)
```
и подобных местах нужно делать подключение модулей явно, то есть в начале файла указывать include и далее путь к миксину который ты подключаешь. Еще раз: структура должна быть древовидной, а не так, что ты подключил все в корне, а потом допустим захочешь переиспользовать этот компонент в другом проекте, а там какие-то модули подключаются не понятно от куда. Этот пункт должен быть осуществлен во всех миксинах.
4. Использовать точечную нотацию для класса:
img(src= src, alt="image", class="headline__image") => img.headline__image(src= src, alt="image")
5. Использовать точечную нотацию; максимальное значение бара передавать сверху параметром, так как у тебя тут не процентное значение; еще раз повторюсь что использование здесь тега `<p>` не семантично, так как он означает абзац текста.
```
mixin software-bar( programm, value)    
    .software-bar
        .software-bar__wrapper
            p.software-bar__headline= programm
            .software-bar__progress
                progress(value= value, max="100", class='software-bar__progress-bar')
```

**Comment by arkhannanov** [comment]
1. Готово.

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
3. Готово.

**Comment by arkhannanov** [comment]
4. Готово.

**Comment by arkhannanov** [comment]
5. Готово.

**Comment by Sergio-Ka** [comment]
Хорошо. Только про var в skills-filled-points забыл. Сделай let.

**Comment by arkhannanov** [comment]
Готово.
