### ISSUE TITLE
Структура папок проекта

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#20]
Наличие папок js и scss кажется сомнительным. 
1. Папка js. Файл favicons.js пустой, а второй файл как я понял относится к настройкам, а потому вряд ли часть проекта на уровне реализации блоков и должен лежать где-то на уровне вместе с вебпаковским конфигом или в нем может быть даже (но тут не уверен). Если он вообще здесь на столько нужен.
2. Папка scss. Шрифты как правило подключаются в файле main либо в самих папка шрифтов как вариант. Переменные можно в globals перенести, а на счет функций - тут вообще сомнительно. Реализация блоков получается уже не независимая, так как часть кишков по идее не зависимых блоков лежит не в них а где-то на стороне из-за чего нарушается компонентность. Там наверняка стилевые правила можно переписать оптимальнее и сэкономить строчки кода лучше там, чем какие-то мелочи в функции выносить.

**Comment by arkhannanov** [comment]
1. Готово
2. Готово

**Comment by Sergio-Ka** [comment]
1. postcss.config.js на уровне вложенности с конфигом вебпака рядом, а не вместе с сурсами, так как это не они, на сколько я понимаю из доков - такое возможно.
2. Ты уж тогда файлик fonts.scss разбей на 3 и положи в каждую папку свой font.scss.
3. Папка scss все еще есть и файлы в ней тоже.
4. Кстати, иконки каждого блока, которые сейчас лежат в общей папке img - это часть реализации блока headline, а стало быть в нем должна быть папка images и эти иконки должны лежать там. faviconы так и остаются на том месте где сейчас, то есть папка img в корне переименовывается в images, так как сокращения это не очень и все в остальном остается так же.

**Comment by arkhannanov** [comment]
1. Не понял немного. Оставить как есть, то есть нормально?

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
4. Готово.

**Comment by arkhannanov** [comment]
3. Готово

**Comment by Sergio-Ka** [comment]
1. нет переместить на уровень с конфигом webpack'а. Остальное нормально.

**Comment by arkhannanov** [comment]
1. Готово.

Единственное что у меня появились Warnings при сборке. Не могу понять откуда возникли.  http://prntscr.com/o0bpgo

Такой папки src/img вообще нет.

**Comment by Sergio-Ka** [comment]
У тебя в конфиге вебпака путь не правильный до конфига postcss (в двух местах указан, смотри внимательно). И там же в конфиге вебпака где настройки CopyWebpackPlugin указан не верный путь до изображений img/favicons, ты же папку переименовал из img в images. Это место и выдает ошибку. Картинки кстати остальные у тебя теперь из другой папки копируются (headline/images) - это тоже место поправить надо. Как исправишь - можешь закрыть этот issue.

**Comment by arkhannanov** [comment]
Исправлено)
