### ISSUE TITLE
Проверить блоки на переполнение

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#21]
![image](https://user-images.githubusercontent.com/33621369/59244384-6d3bb000-8c3e-11e9-9aed-d5154f2294aa.png)
В стандартах есть на эту тему. В таких случаях нужно чтобы слова переносились. Не красиво, но все еще читабильно. Проверить для всего проекта как ведут себя блоки на длинных словах. А потом еще раз на адаптивность глянуть, а то бывают эксцессы.

**Comment by arkhannanov** [comment]
Исправил. Кое-где подправил стили, где-то добавил word-break: break-all.

**Comment by Sergio-Ka** [comment]
Заголовки блоков и названия программ все еще не очень:
![image](https://user-images.githubusercontent.com/33621369/59404786-1961d000-8dd2-11e9-8443-c45c9603e1da.png)

**Comment by arkhannanov** [comment]
Просто я по смыслу проверял. Просто вряд ли возможно что наименование заголовков будет таким длинным, так и название программ.

**Comment by arkhannanov** [comment]
Исправлено)
