### ISSUE TITLE
Оптимизировать, поправить CSS

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#22]
```
.avatar {
  width:100%;
  width: 100%;
  text-align: center;
  display: flex;
  flex-direction: column;
  justify-content: center;
  margin-bottom: 3.333rem;
  margin: 0; 
  font-family: $boldFont;
  margin-top: 0.8rem; 
  margin-left: 0.65rem;
  margin-bottom: 4.8rem; 
```
1. Глянь лишние дублирующиеся css правила. В примере выше у тебя дважды указаны width и  margin-bottom и там же еще до кучи указываешь margin 0. Тебе не кажется, что это взаимоисключающие директивы? Вообще по факту будут работать только последние правила. Это все выглядит неряшливо.
2. ты задаешь ширину блока в 100%, хотя для div нормальное поведение и так занимать всю ширину. Например в avatar 2 раза width:100%;, в profile 1 раз и так далее.
3. Ты указываешь правило font-family хотя оно наследуется и для всего проекта достаточно навешать его на html, а не писать в каждом блоке. Чтобы переопределять начертание достаточно указывать font-weight или font-style или оба если необходимо (если у тебя все корректно описано в дерективе font-face, а у тебя сейчас описано плохо). Ты указываешь одинаковые названия шрифтов в директиве @font-face и для каждого из подключаемых шрифтов так же указываешь там же font-weight и font-style, а когда тебе нужно указать непосредственно например жирный шрифт для какого-то блока - там указываешь font-weight - и тогда подтягиваются те файлы шрифта которые нужны - так это работает. Из того как сделано сейчас у тебя, я могу сделать вывод, что ты либо этого не знаешь, либо не понимаешь и стоит тогда еще поизучать теорию на эту тему.
4. задавать фиксированную высоту блокам - признак плохого кода. И в стандартах про это есть. Обычно такие вопросы решаются высотой контента, плюс padding.
5. Недопустимо вешать внешнее поведение на блоки БЭМ (в частности margin'ы), то есть они не должны влиять на свое окружение. Вопросы позиционирования решаются как я уже указывал с помощью оберток, которые являются БЭМ элементами родительского блока. Так же нельзя использовать для этих целей padding'и. Хотя формально они допустимы, но если ты ими отступы задаешь какие-то от внешних элементов - это плохо. То есть ты если задаешь padding, то если ты берешь этот блок и вставляешь в другой проект, то они не должны меняться, то есть они должны быть частью внешнего вида блока. в таком случае можно использовать их.
6. Нельзя позиционировать с помощью left и top относительно позиционированые элементы. Это есть в стандартах.
```
&__name {
    line-height: 80%;
    letter-spacing: 0.208rem;
    font-family: $lightFont;
    top: 2.3rem;
    left: 0.1rem;
    font-size: 3.333rem;
    margin-block-start: 0;
    margin-block-end: 0;
    position: relative;
    text-transform: uppercase;
  }
```
7. Нельзя задавать отрицательные значения для margin. Не очевидное поведение. Это есть в стандартах.
```
  &__items-list {
    width: 100%;
    margin-bottom: -26%;
    margin-top: -0.5rem;
  }
```
8. Вендорные префиксы должны идти перед общим стилем. Это есть в стандартах. А вообще в них и нет даже особой-то необходимости. По расстановке их может помочь например autoprefixer, хотя если охота время тратить, то можно. Но перед общим стилем.
```
html {
  line-height: $mainLineHeight;
  font-size: $mainFontSize;
  color: $mainFontColor;
  max-width: 1920px;
  min-width: 320px;
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  -moz-hyphens: auto;
  -webkit-hyphens: auto;
  -ms-hyphens: auto;
```
9. Вообще рекомендую еще раз посмотреть стандарты fsd. Кроме того, то что сверху описано - применить ко всему проекту и последующим.

**Comment by arkhannanov** [comment]
1. Готово.

**Comment by arkhannanov** [comment]
2. Готово.

**Comment by arkhannanov** [comment]
3. Готово.

**Comment by arkhannanov** [comment]
4. Посмотрел, вроде блокам у меня height не задано. height используется только для окружностей и высоты полосок.

Есть в одном месте только.

**Comment by arkhannanov** [comment]
5. Готово.

**Comment by arkhannanov** [comment]
6. Готово.

**Comment by arkhannanov** [comment]
7. Избавился от отрицательных марджинов. 

После такого обширного рефакторинга у меня все становится по полочкам))

**Comment by arkhannanov** [comment]
8. Готово. У меня на самом деле уже конфиг postcss.config.js содержит autoprefixer.

**Comment by arkhannanov** [comment]
9. Вроде все перечитал.

Единственное не совсем понял по min-width, это абсолютно везде нужно заменить где есть width, верно?

https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/generalRequirements.md (Пункт 9).

**Comment by Sergio-Ka** [comment]
1. Давай еще маленько причешим, хотя стало лучше. Например:
```
  &__text {
    color: $borders;
    margin: 0;
    font-size: 2.58rem;
    letter-spacing: 0.063rem;
    font-weight: bold;
    vertical-align: middle;
    text-transform: uppercase;
    margin-left: 0.58rem;
    word-break: break-all;
    margin-bottom: 0.3rem;
  }
```
Здесь три правила margin разбросаны по блоку, сначала margin 0, потом отдельно для левой стороны, отдельно для низа, почему бы не сделать так:
```
margin 0 0 0.3rem 0.58rem
```
Меньше знаков на экране - легче воспринимается и быстрее и не только тобой, но и тем кто твой код смотрит или использует. Тут глянуть стоит еще раз по всему css. Вообще можно многие свойства сводить к коротким записям, если они такое допускают. margin, padding, border, background - например, как самые часто встречающиеся. Если проделать это все - у тебя сильно css похудеет, что будет хорошо.

2. В list-item много где строка встречается color:$mainFontColor; цвет текста наследуется. Его надо указывать у родителя типа body или html и только когда он отличается - переназначать. А так лишние правила, лишний текст. Так же это касается background-color: #FFF; и вообще цвета фона, тем более что он у тебя вообще везде белый, смысла его в каждый блок тыкать нет никакого. Ну там для бара, но это скорее исключение. А background: none; у html не нужен. Ты вот ему задай #FFF и все. А то еще стоит подумать нужен ли он вообще, он так-то по умолчанию белый.

3. Пустые блоки надо удалять:
```
  &__content-container {
    
  }
```
Так же посмотреть в целом форматирование, где-то строки пустые посреди правил блока стоят, где-то пробелов недостает. В целом только правила блоков должны пустыми строками отделяться, медиазапросы так же.

4. По поводу min-width. Можно заменить, если верстка не ползет. Просто нужно понимать какое тебе это дает преимущество. Как правило это означает, что блок будет не со статичной шириной, а будет расширятся если будет необходимо, но при этом будет иметь минимальную ширину.

**Comment by arkhannanov** [comment]
1. Готово

**Comment by arkhannanov** [comment]
2. Готово

**Comment by arkhannanov** [comment]
3. Готово

**Comment by arkhannanov** [comment]
4. Понял

**Comment by Sergio-Ka** [comment]
3.1 Блок avatar  лишняя строка посреди правил блока:
```
  &__border {   
    margin: auto;
    width: 14.817rem;
    height: 14.817rem;
     
    border: 0.083rem solid $borders;
    border-radius: 50%;
```
3.2 Блок contact, медиазапросы разделить пустой строкой.
```
      @media screen and (max-width: $smDesktopWidth) {
        width: 7.292rem;
        font-size: 1rem;
      } 
      @media screen and (max-width: 510px) {
        width: 4.292rem;
        font-size: 1rem;
```
3.3 Блок list-item медизапросы разделить пустой строкой
```
    @media screen and (max-width: $desktopWidth) {
      height: 1rem;
      width: 1rem;
    }
    @media screen and (max-width: $tableWidth) {
      height: 0.833rem;
      width: 0.833rem;
    }   
```
Лишняя пустая строка перед закрывающей фигурной скобкой
```
  &__degree_black  {   
    margin-block-start: 0;
    margin-block-end: 0;
    color: $mainFontColor;
    font-weight: bold;
    font-size: 1.667rem;
    text-transform: uppercase;
    line-height: 1.7rem;

  }
```
Эти замечания отработаешь, можешь сам этот issue закрыть. На этом думаю с первым проектом всё.

**Comment by arkhannanov** [comment]
Готово! Круто, спасибо! Ура!)
