### ISSUE TITLE
Реализовать автоматический импорт стилей

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#3]
Сейчас у тебя 
@import "../blocks/block_avatar/avatar.scss";
@import "../blocks/block_profile/profile.scss";
@import "../blocks/block_contact/contact.scss";
@import "../blocks/block_skills/skills.scss";
@import "../blocks/block_education/education.scss";
@import "../blocks/block_experience/experience.scss";
@import "../blocks/block_software/software.scss";
Сделай так, чтобы у тебя в точке входа функция реквайрила твои стилевые файлы, файлы js, файлы картинок, чтобы не приходилось помнить о каждом и подключать его вручную.

**Comment by arkhannanov** [comment]
Сделано.

**Comment by Sergio-Ka** [comment]
Не, как сделано не пойдет. Импорты остались во-первых в стилевых файлах. Во-вторых импортить стоит не только стилевые файлы, но js и картинки. Посмотри в сторону регулярок для описания путей импорта и типов файлов, которые смогут импортиться. Это у тебя сейчас 7 блоков в резюме, а если например ты захочешь подключить еще какие нибудь новые блоки? Если будет такая функция, то твое подключение в данном случае будет заключаться в указании include, а если без функции, то надо будет помнить о стилях так же и картинках и js, что как минимум не удобно.

**Comment by arkhannanov** [comment]
1. У меня проблема с подлючением шрифтов. Когда включаю блок:

function importAll(resolve) {
    resolve.keys().forEach(resolve);
  }
  
importAll(
    require.context('./scss', true, /\.(scss)$/)
  );
Шрифты не находятся.

2. js-файлы подключать по такому же принципу как и scss?
3. Картинки подключать по такому же принципу как scss?

Не понял этот блок: "Посмотри в сторону регулярок для описания путей импорта и типов файлов, которые смогут импортиться. Это у тебя сейчас 7 блоков в резюме, а если например ты захочешь подключить еще какие нибудь новые блоки? Если будет такая функция, то твое подключение в данном случае будет заключаться в указании include, а если без функции, то надо будет помнить о стилях так же и картинках и js, что как минимум не удобно."

В данном случае идет речь об автоматизации подключения pug - файлов?

**Comment by arkhannanov** [comment]
Проблема со шрифтами была решена подключением плагина 'resolve-url-loader', а то не читались относительные url.

Теперь все хорошо с подключением scss без импортов.

А как быть с картинками и js? Также подключать? Через:

function importAll(resolve) {
    resolve.keys().forEach(resolve);
  }
  
importAll(require.context('./', true, /\.(scss|png|js)$/));

Спасибо за ответ.

**Comment by Sergio-Ka** [comment]
Зачем у тебя сейчас в файле index.js вот эти 2 строки?
import './js/favicons.js'
import './main.scss'

Содержимое favicons.js нужно переписать в index.js, сам файл убрать. В смысле чтобы вся эта функциональность по импорту файлов была в одном файле index.js.

**Comment by arkhannanov** [comment]
Исправлено.
