### ISSUE TITLE
Тэги не должны быть без классов и точечная нотация

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#4]
```   
.skills-dots-wrapper
  div.skills-dots-wrapper__headline
    p= headline
```
У тебя здесь в одном месте указан div, а в другом выше нет. Сделай единообразно без div по всему проекту. Тэг р у тебя здесь голый без классов. По стандартам FSD тэги не должны быть без классов ([html.тэги.п11](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78iae/)). Просмотри так же по всему проекту.

**Comment by arkhannanov** [comment]
Сделано

**Comment by Sergio-Ka** [comment]
У тебя там один `<img>` в headline не имеет класса, о чем я написал в другом issue уже. Как добавишь, можешь закрыть это issue.

**Comment by arkhannanov** [comment]
Сделано. #6 Refactoring.
