### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#5]
```
h2.h2 NAME HERE
h1.h1 SURNAME
h3.h3 GRAPHIC DESIGNER
```
Здесь классы мало того что нарушают БЭМ они имеют очень плохое название. Именование (это касается не только именования классов CSS как сущностей БЭМ, но и именования переменных в js) должно быть осмысленным, коротким и описывающем сущность, но при этом не завязанным на ее внешний вид. Нужно изучить на ru.bem.info соглашение по именованиям еще раз и [стандарты.js.хорошие практики.п3](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_9aii8/), а так же [стандарты.css.БЭМ.п1](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_9aii8/). То есть в данном случае для примера этот блок кода должен был выглядеть как-то так:
```
.avatar__name NAME HERE
.avatar__surname SURNAME
.avatar__profession GRAPHIC DESIGNER
```
Кроме того тэги h1, h2, h3 здесь явно не семантичны, так как это не заголовки в данном случае. Есть пункт в стандартах на тему семантичности ([html.семантика.п8](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78iae/)). Думаю достаточно просто будет сделать без них здесь. Кстати, если ты проверишь на предмет семантичности остальную часть проекта в рамках этого issue, то еще одного issue не возникнет.

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Frolikow** [comment]
По поводу именования, есть много замечаний:
1) При именовании папок с файлами слово `block` лишнее, и так ведь все лежит в папке `blocks`

2) Если у тебя миксин, например, `contact` , то в нем должен лежать блок `contact`, а ни как не `contact-wrapper`. И файл должен тогда называться `contact`, и папка в которой этот файл лежит тоже `contact`

3) Что за миксин `contact_line`. из названия понятно что это модификатор `line` для блока `contact`. Но чтобы понять что это на самом деле блок, приходиться шарить по коду. Недопустимое название для миксина

4) Каждый блок должен быть в отдельном миксине. Касается, например, этого места: 
https://github.com/arkhannanov/FSD_CV/blob/e97222a5e58be9d5eeba17760c24ebd70d6d6b71/src/blocks/block_education_item/education_item.pug#L4

Это не конкретные проблемы, они касаются всего проекта. Проверь внимательно везде. Если что-то не понятно - то лучше 

>   изучить на ru.bem.info соглашение по именованиям еще раз

**Comment by arkhannanov** [comment]
Названия исправлены.

**Comment by Frolikow** [comment]
Здесь не исправил:
![image](https://user-images.githubusercontent.com/25764783/58391202-fb207400-805e-11e9-9d40-6a8e2915dcea.png)
![image](https://user-images.githubusercontent.com/25764783/58391212-05427280-805f-11e9-8a31-7f370321fe97.png)

Тут не понятно, почему элемент делающий одно и тоже в каждом блоке, где-то называется picture, а где-то headline.
https://github.com/arkhannanov/FSD_CV/blob/78acae5a3162463b5c3bdc96b8ebe29de5f21e0c/src/blocks/profile/profile.pug#L3
https://github.com/arkhannanov/FSD_CV/blob/78acae5a3162463b5c3bdc96b8ebe29de5f21e0c/src/blocks/skills/skills.pug#L3

Этот вопрос все еще не решен
https://github.com/arkhannanov/FSD_CV/blob/78acae5a3162463b5c3bdc96b8ebe29de5f21e0c/src/blocks/education-item/education-item.pug#L4

**Comment by arkhannanov** [comment]
Исправил. Что касается последнего вопроса. Правильно ли я понял, что у меня неправильно указан класс .dot. Мне нужно назвать его по БЭМ или вообще нужно вынести в отдельный миксин эту точку?

Сейчас исправил наименование класса.

**Comment by Frolikow** [comment]
> Исправил. Что касается последнего вопроса. Правильно ли я понял, что у меня неправильно указан класс .dot. Мне нужно назвать его по БЭМ или вообще нужно вынести в отдельный миксин эту точку?
> 
> Сейчас исправил наименование класса.

Весь проект должен быть по БЭМу. Если все сделано по конкретным правилам, то в коде гораздо легче разбираться, легче рефакторить и легче расширять(при необходимости).

**Comment by Frolikow** [comment]
Идем дальше) 
```pug
.experience-item__content
    .experience-item__content-1line
        p.experience-item__company-name= company_name
            span.experience-item__date= date
    .experience-item__content-2line
        p.experience-item__job= job
    .experience-item__content-3line
        p.experience-item__container= content
```
`1line, 2line, 3line` - почему так?
если я захочу стили поменять, например,  для `job` поменять? как в стилях я пойму какая из этих *`line` относиться к строке `job` ?

**имена должны отображать смысл, а не описание стилей** 
[Стандарты(пункт 13)](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/generalRequirements.md)

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/58413447-009fad80-80a3-11e9-9404-1c522e817176.png)
имя миксина != имя блока )

**Comment by arkhannanov** [comment]
Исправлено.

**Comment by Sergio-Ka** [comment]
1. Не используй цифры в именовании переменных, это плохая практика (ни здесь, ни в js). Назови переменную по смыслу. Не говоря уже о том что здесь отыменовано так, как будто это элемент элемента, что по БЭМ не допустимо.
.contact__item__container1
a.contact__item__container2
2. Здесь
.skills-dots
именование лучше сделать более абстрактным. Если ты захочешь убрать border-radius и сделать кругляши квадратами? Это получится у тебя будет не .skills-dots, а .skills-square уже. То есть тут нужно подумать над именованием данной сущности.
![image](https://user-images.githubusercontent.com/33621369/58452175-9a696800-8140-11e9-9e19-e7152708df3f.png)

**Comment by arkhannanov** [comment]
1. contact__item - блока уже не должно быть, удалил и переписал его по-другому.
2. .skills-dots заменено на .skills-filled-points

**Comment by Frolikow** [comment]
В pug'е, переменные следует именовать в стиле camelCase. Проверь весь проект на это.

**Comment by Frolikow** [comment]
> Не используй цифры в именовании переменных, это плохая практика (ни здесь, ни в js). Назови переменную по смыслу.

![image](https://user-images.githubusercontent.com/25764783/58695767-643a1b80-83c0-11e9-8900-074f76a89aeb.png)
![image](https://user-images.githubusercontent.com/25764783/58695782-6a2ffc80-83c0-11e9-9bde-7458b080ec7b.png)

**Comment by arkhannanov** [comment]
Готово. Исправлено.

**Comment by Frolikow** [comment]
Это не исправлено.
> В pug'е, переменные следует именовать в стиле camelCase. Проверь весь проект на это.

Тебе не кажется что это почти тоже самое получилось?) в именах переменных теперь есть смысл? их названия описывают то что в них лежит?) мне так не кажется)
 
https://github.com/arkhannanov/FSD_CV/blob/bda759bfadb084000b3f8bbaa2ad5495417dfb73/src/blocks/page/page.pug#L68-L82

Вообще, сейчас у тебя эти участки кода можно оформить гораздо красивее и логичнее. 
Например так:
```pug
+software({
    headline:{
        source: "./img/software-icon.png",
        title: "software", 
    },
    skills: [
        {skill: "photoshop", level: "91" },
        {skill: "illustrator", level: "70"},
        {skill: "indesign", level: "55" },
        {skill: "dreamweaver", level: "84"},
        {skill: "after effects", level: "62" },
        {skill: "html&css3", level: "91"},
    ]
})
```
а внутри миксина объект для заголовка передать заголовку, а по массиву со скилами пройтись циклом)

**Comment by arkhannanov** [comment]
Готово)

**Comment by Frolikow** [comment]
> Это не исправлено.
> 
> > В pug'е, переменные следует именовать в стиле camelCase. Проверь весь проект на это.

**Comment by Frolikow** [comment]
```pug
.contact__item__container-header address 
a.contact__item__container-content= address
```
что это за элементы?

**Comment by Frolikow** [comment]
```pug
.education-item__content
    .education-item__content-degree
        p.education-item__degree= degree
            span.education-item__date= date
    .education-item__content-university-name
        p.education-item__university-name= university_name
    .education-item__content-content
        p.education-item__content= content
```

у тебя есть элемент `.education-item__content`. Зачем внутри везде дублировать  слово  `content` в названиях? получается лишняя привязка к имени родительского контейнера. Если тебе необходимы обертки на параграфами, то называй их по смыслу, например, `.education-item__university-name-wrapper`

**Comment by arkhannanov** [comment]
> ```
> .contact__item__container-header address 
> a.contact__item__container-content= address
> ```
> 
> что это за элементы?

Это название левой части строки, название, а справа передается что конкретно в этой строке. Ведь название левой колонки не меняется.

**Comment by arkhannanov** [comment]
2-e исправлено.

**Comment by Frolikow** [comment]
> > ```
> > .contact__item__container-header address 
> > a.contact__item__container-content= address
> > ```
> > 
> > 
> > что это за элементы?
> 
> Это название левой части строки, название, а справа передается что конкретно в этой строке. Ведь название левой колонки не меняется.

Если не сложно, то именно про классы этих двух элементов расскажи) Какие из слов какой имеют смысл  контексте БЭМа?

**Comment by arkhannanov** [comment]
.contact__item__container-header - заголовок строки address
.contact__item__container-content - контент стоки adrsress

**Comment by Frolikow** [comment]
> .contact__item__container-header

что в данном случае `contact`, что `item` и что `container-header `
опиши плиз

**Comment by arkhannanov** [comment]
contact - блок contact в целом
contact__item - строка (элемент) в блоке contact
.contact__item__container-header - контейнер заголовка строки (элемента) блока contact (заголовок строки слева от содержимого строки)
.contact__item__container-content - контейнер содержимого строки (элемента) блока contact

**Comment by Frolikow** [comment]
Спасибо за описание)
Теперь главный вопрос: БЭМ допускает именование по такому шаблону как у тебя? Рекомендую внимательно изучить именование в БЭМе.

**Comment by arkhannanov** [comment]
Всего 3 принципа БЭМ:
1. Вложенность
2. Принадлежность
3. Необязательность

1.1Элементы можно вкладывать друг в друга.
1.2.Допустима любая вложенность элементов.
1.3 Элемент — всегда часть блока, а не другого элемента. Это означает, что в названии элементов нельзя прописывать иерархию вида block__elem1__elem2.

2.1 Элемент — всегда часть блока и не должен использоваться отдельно от него.

3.1 Элемент — необязательный компонент блока. Не у всех блоков должны быть элементы.

Не совсем понимаю какому принципу противоречит моя запись? Можно, наверное, разве что слово container убрать.

Просьба прояснить.

**Comment by Frolikow** [comment]
твоя запись противоречит пункту 1.3 :
```pug
.contact__item__container-header address 
a.contact__item__container-content= address
```
> 1.3 Элемент — всегда часть блока, а не другого элемента. Это означает, что в названии элементов нельзя прописывать иерархию вида **block__elem1__elem2**.

**Comment by arkhannanov** [comment]
Ой) Вот это да!) А слона то я и не приметил) Ок, хорошо, спасибо. Исправлю!

**Comment by Frolikow** [comment]
> Ой) Вот это да!) А слона то я и не приметил) Ок, хорошо, спасибо. Исправлю!

Бывает)

___


Вот это еще поправь
> > Это не исправлено.
> > > В pug'е, переменные следует именовать в стиле camelCase. Проверь весь проект на это.

**Comment by arkhannanov** [comment]
Готово)

**Comment by Sergio-Ka** [comment]
1. Посмотри в стандартах как именуются подключаемые файлы по умолчанию если не выдано каких-то предварительных установок (а их в данном случае не выдано) и как у тебя сейчас отыменованы шрифты и папки на пути к ним и исправь.
2. Плохое именование во всем блоке education-experience-item. Во-первых слишком длинное название, во вторых оно завязано на конкретные блоки education и experience. Что мешало обозвать эту сущность каким-нибудь list-item, а сами места где происходит подключение не __items-container, а например items-list - решительно не понятно.

**Comment by arkhannanov** [comment]
1. Готово.
2. Готово.

**Comment by Sergio-Ka** [comment]
1. Не готово. Подключаемые файлы именуются в стиле lower-case-hyphenated, а у тебя и шрифты и папки их с большой буквы. Если же ты так сделал, то тогда проблема у тебя в настройках гита, он по умолчанию не различает строчные и прописные буквы.
2. Все еще громоздко, неужели ты сам не видишь, что такие монструозные имена сложны для восприятия?
```
firstLineFirstPositionColor,firstLineFirstPositionContent
.list-item__first-line-first-position-content-wrapper
```
Во-первых, зачем тут обертки, если без них все работает прекрасно, во-вторых я все еще продолжаю считать что тег `<p>` семантичен для абзацев текста, а не просто каких кусков. В-третьих, от того что ты заменил числа в именах на числа написанные словами суть не поменялась, то есть твое `.list-item__first-line-first-position-content-wrapper` по факту есть `.list-item__1-line-1-position-content-wrapper`. А теперь самое время вспомнить, что писалось по поводу использования чисел в именах переменных и прочих сущностей.

**Comment by arkhannanov** [comment]
1. Готово

**Comment by arkhannanov** [comment]
2. Готово

**Comment by Sergio-Ka** [comment]
Ну ведь гораздо же лучше стало, и воспринимается легче.
