### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Sergio-Ka** [arkhannanov/FSD_CV#6]
```
.avatar
    .avatar-wrapper
        div.avatar__avatar-border 
            div.avatar__avatar-photo 
        h2.h2 NAME HERE
        h1.h1 SURNAME
        h3.h3 GRAPHIC DESIGNER
```
Это явно не БЭМ, точнее не совсем. Нужно изучить еще раз теорию БЭМ на ru.bem.info. Стандарты fsd указывают на явное использование БЭМ ([стандарты.css.БЭМ](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78ial/)). Только у fsd не используются миксы, позиционирование блоков делается через обертки (которые как правило элементы (по БЭМ) родительских блоков). У тебя блок avatar-wrapper в блоке avatar. При этом блок avatar-wrapper сам по себе смысл не имеет, если он тут вообще нужен - то это явно должен быть элемент, а не блок. Кроме того заголовки у тебя здесь реализованы как отдельные блоки - хотя по смыслу это явно элементы блока avatar.
Так же структура директорий должна быть плоской. То есть все блоки БЭМ с их реализациями должны лежать каждый в своей папке и на одном уровне, то есть без вложенности папок в папки. Элементы не нужно выделять в папки как это сделано сейчас у тебя. Если у тебя некая функциональность используется не в одном месте, а в нескольких - то это явно блок по БЭМ и его можно выделить в отдельную папку (типа как expirience/education или заголовки у блоков с иконками).

**Comment by arkhannanov** [comment]
Исправлено. Теперь структура директорий плоская.

**Comment by Sergio-Ka** [comment]
1. Здесь:
```
mixin headline( src, text)  
    .headline
        .headline__image
            img(src= src)
        h3.headline__text= text
        .headline__line
```
тэг `<img>` у тебя без класса и без атрибута 'alt', который нужно использовать обязательно в соответствии со стандартами fsd ([Стандарты. HTML. Тэги. п.13](https://rizzoma.com/topic/a87a0a28b84d6326d4f3909e8801dab7/0_b_8nel_78iae/)).
2. Где у тебя в блоках include - делай их в начале файла, а не в месте, где миксин вызываешь. Это не БЭМ требование, но так принято. Потом в реакт компонентах ты импорты будешь так же делать в начале файла. Про это есть в стандартах.
3.  Тут вообще не понятно что:
```
.contact__item
        .contact__item__container1 address 
        a.contact__item__container2 Main Street, City.
```
.contact__item__container1 это что? Элемент элемента? БЭМ такое допускает?
4. БЭМ распространяется сюда тоже:
```
    main.page
            .wrapper
                section.left-col
```
У тебя тут три вложенных блока БЭМ? Хотя по логике это явно должен быть один блок с элементами. А левая и правая колонка  - это явный намек на использование модификаторов, то есть должно быть что-то типа:
```
 main.page
            .page__wrapper
                section.page__column.page__column_position_left
                section.page__column.page__column_position_right
``` 
И оформлено это должно быть так же как и прочие блоки БЭМ - то есть в папку. А в index.pug у тебя будет только заголовок и body и ты будешь вызывать этот миксин со всеми кишками. Кстати с точки зрения БЭМ все реализации блока должны лежать в одном месте. То есть у тебя сейчас с index.pug на одном уровне должен лежать как минимум файл со стилями, описывающими стили html, body.

**Comment by Sergio-Ka** [comment]
Здесь кстати то же самое что и выше написал:
.software__items-left-column

**Comment by arkhannanov** [comment]
Готово.

**Comment by Frolikow** [comment]
```pug
mixin headline( src, text)  
    .headline
        .headline__image
            img(src= src, alt="image", class="image")
        h3.headline__text= text
        .headline__line
```
теперь получился блок внутри блока

**Comment by arkhannanov** [comment]
Готово.
