### ISSUE TITLE
Чистка проекта

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#7]
Нужно удалить все `console.log`. Удалить все комментарии в коде, если они не несут смысла(если информация в комментариях - ее всегда можно посмотреть в истории)

**Comment by Frolikow** [comment]
Так же в стилях есть куча импортов. В том числе закоменченых, если они не нужны - удаляй.

**Comment by arkhannanov** [comment]
Готово.

**Comment by Frolikow** [comment]
Для какой цели нужен файл  `main.css` в папке `css`? Если лишний - на удаление.

**Comment by arkhannanov** [comment]
Готово.

**Comment by Frolikow** [comment]
Комментарии захламляющие проект недопустимы 
https://github.com/arkhannanov/FSD_CV/blob/2bb213ca42e11527dbf4b98ba7e64e2235dbb072/src/blocks/experience/experience.pug#L12-L15
