### ISSUE TITLE
px to rem

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#8]
Не стоит указывать размеры в пикселях без важной на то причины [(стандарты.шрифты.пункт 5)](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/fonts.md)

**Comment by arkhannanov** [comment]
Исправил где возможно на rem. В остальных случаях у меня в основном указываются $min-font-size и $max-font-size для функции @mixin fluid-type($min-vw, $max-vw, $min-font-size, $max-font-size). Эта функция уменьшает/увеличивает размер шрифта в зависимости от размера экрана https://css-tricks.com/snippets/css/fluid-typography/.

**Comment by Frolikow** [comment]
Небольшая просьба, когда пушишь комиты, пиши #[номер ишью]. 
В твоем случае нужно не пропускать пробел перед #. Тогда из каждого ишью будут видны соответствующие комиты

**Comment by Frolikow** [comment]
> На элементах без специфичных требований (не фиксированные пиксели и не относительно области экрана) использовать rem, изучить по максимуму чем отличаются px, pt, em, rem, vh, vw, vmin, vmax и их использовать в остальных случаях;

Тут именно об **элементах** речь, не только шрифты. 
Сейчас верстка себя странно ведет при уменьшении разрешения
![image](https://user-images.githubusercontent.com/25764783/58371790-bf8e8880-7f3e-11e9-9f26-7dfff6400adb.png)

**Comment by arkhannanov** [comment]
Размеры элементов исправлены на rem.

**Comment by arkhannanov** [comment]
Отредактирована адаптивность.

**Comment by Frolikow** [comment]
На счет адаптивности. для картинок в блоках `headline` тоже добавь адаптивности. И при малом разрешении - боковые отступы лучше сделать меньше, а то одна колонка узкая по экрану.

**Comment by arkhannanov** [comment]
Сделано.

**Comment by Frolikow** [comment]
это закрываю, по адаптивности потом отдельно создам ишью

**Comment by Sergio-Ka** [comment]
На мой взгляд не очень с px обстоит, issue рано закрыто. Много мест где используются пиксели, но это не обязательно. На счет функции которая там с размером шрифта что-то делает - по нормальному это делается через rem как раз таки и через медиазапросы.

**Comment by arkhannanov** [comment]
Брал прием отсюда https://css-tricks.com/snippets/css/fluid-typography/

То есть размер шрифта автоматически пересчитывается в зависимости от размера экрана. А как это сделать с помощь медиа-запросов, ведь там только фиксированный размер шрифта можно задать.

Ну что? Удалять этот миксин?

**Comment by Sergio-Ka** [comment]
Вообще непонятно в чем необходимость изменения размера шрифта? Он остается достаточно читабельным при разных размерах экрана. И если уж где-то тебе там на мелких размерах нужно сделать и шрифт мелким, то для всего шрифта ты задаешь размер в rem, а когда делаешь перестроение для мелкого экрана - вешаешь медиазапрос на html и там просто у размера шрифта меняешь его на более мелкий, можно так сделать несколько раз. Пока не приходилось сталкиваться с необходимостью изменения размера шрифта в зависимости от размера экрана. НУ и кроме того по факту когда через вебпак и модули эта ерунда пропустится - на выходе будет статичный css файл, а вся динамика твоя может быть нормально описана в каждом блоке без всяких функций препроцессора. Которые к тому же плохо воспринимаются в отрыве от блоков.

**Comment by arkhannanov** [comment]
Ага, понятно. Сейчас поправлю)

**Comment by arkhannanov** [comment]
Исправлено)

**Comment by Sergio-Ka** [comment]
Не исправлено. Все еще куча мест где используются пиксели. Например 4 места только в блоке avatar насчитал. Хотя там не только он. А вот такие вещи `line-height: 0.9;` без указания единиц по факту означают em, а это плохо.

**Comment by arkhannanov** [comment]
Готово)

**Comment by Sergio-Ka** [comment]
В двух местах line-height указан без единиц измерения, посмотри поиском. И где константы - тоже. $mainLineHeight          : 1.4; Там же кстати размеры заданы в пикселях $desktopWidth            : 1280px;
$smDesktopWidth          : 980px;
$tableWidth              : 768px;
$phoneWidth              : 480px;
$smPhoneWidth            : 320px;

**Comment by arkhannanov** [comment]
$smDesktopWidth : 980px;
$tableWidth : 768px;
$phoneWidth : 480px;
$smPhoneWidth : 320px;

Так это же ширина девайсов, если она будет в rem, то будет меняться. Точно исправлять? В медиазапросах я тоже пиксели ставил, это неправильно? Исправить тоже на rem?

**Comment by arkhannanov** [comment]
По поводу $mainLineHeight : 1.4 в учебнике пишут что лучше задавать именно через множитель https://learn.javascript.ru/font-size-line-height, так как высота строки рассчитывается от размера шрифта, только в редких случаях фиксированный размер.

Если поставить фиксированный размер строки, то придется подбирать высоту строк в каждой строке проекта. Это правильно?

**Comment by Sergio-Ka** [comment]
Если ширина девайсов указана в пикселях, то можно оставить. На счет высоты строк - смотри про размеры в стандартах. Учебник написан для широкой аудитории и не все что там есть соответсвует тому, что написано в стандартах fsd. Как я уже сказал, безразмерная величина - это по факту единица измерения em и не очевидное поведение, то есть нужно переделать на rem. НА счет того что придется подбирать высоту - ее приходится подбирать в любых единицах измерения.

**Comment by arkhannanov** [comment]
Готово.

**Comment by Sergio-Ka** [comment]
Можно закрыть этот issue.
