### ISSUE TITLE
блок contact

### ISSUE THREAD

**Issue by Frolikow** [arkhannanov/FSD_CV#9]
Тут кажется проблемы с выравниванием при уменьшении разрешения экрана
![image](https://user-images.githubusercontent.com/25764783/57999632-3fac8c80-7b00-11e9-90a6-6dd3e244f00f.png)

И ошибка реализации элементов этого блока. Перечитай еще раз [стандарты HTML.теги](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md)

**Comment by arkhannanov** [comment]
Исправлено. Сейчас все отображается корректно.

**Comment by Frolikow** [comment]
> И ошибка реализации элементов этого блока. Перечитай еще раз стандарты HTML.теги

Пропустил?

**Comment by arkhannanov** [comment]
Немного не понял ошибку. Сейчас у меня одна линия реализуется миксином:

mixin contact-line( position1, position2)
    .contact-line
        .contact-line__container1= position1 
        .contact-line__container2= position2

Должно два слова идти в одном теге?

**Comment by Frolikow** [comment]
тут главная ошибка, на которую я указывал - это:

![image](https://user-images.githubusercontent.com/25764783/58390877-93b5f480-805d-11e9-9319-ff399007ac77.png)
в твоем случае просто текст написан. 

Плюс к этой задаче (касается Всего проекта)
![image](https://user-images.githubusercontent.com/25764783/58390918-c52ec000-805d-11e9-8c62-328bead24fa8.png)

**Comment by arkhannanov** [comment]
Сделано.

**Comment by Frolikow** [comment]
+ А можешь объяснить что ты сделал с ссылками? И почему именно так решил сделать? 

+ Внимательно проверь Весь проект. Какой смысл где-то писать КАПСОМ если это можно сделать стилями?

**Comment by arkhannanov** [comment]
1. Добавил ссылку a href = position2.

mixin contact-line( position1, position2)
    .contact-line
        .contact-line__container1= position1 
        a(href= position2, class= "contact-line__container2")= position2

Ведь просто заглушки ставить нельзя, добавил ссылки. Неправильно сделал?

2. Капсом оставил как в первичной редакции.  text-transform: uppercase везде где нужно добавил.
Неправильно? Нужно переписать на маленькие?

**Comment by Frolikow** [comment]
1) [Стандарты](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md). Особое внимание обрати на 24 пункт этого раздела. Думаю вопросы отпадут сами собой)
2) Когда в верстке встречаешь подобное:
```pug
+avatar("NAME HERE", "SURNAME", "GRAPHIC DESIGNER")
```
честно, выглядит как-будто константы какие-то) 
Это есть в [стандартах пункт 12](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md).

**Comment by arkhannanov** [comment]
Пункт 1 выполнен.

**Comment by arkhannanov** [comment]
Пункт 2 выполнен.

**Comment by Frolikow** [comment]
+ Еще на счет ссылок:  [Стандарты пункт 15,16](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md)

+ ![image](https://user-images.githubusercontent.com/25764783/58451598-48274780-813e-11e9-8a14-2db5998ee661.png)

**Comment by arkhannanov** [comment]
Готово. Большие буквы были полностью заменены в рамках другого ишью.

**Comment by Frolikow** [comment]
В стилях  блока, зачем-то заданы стили для ссылки по тегу. Это плохо. У тебя ведь ссылка с классом даже

**Comment by Frolikow** [comment]
В стилях блока, зачем-то заданы стили для ссылки по тегу. Это плохо. У тебя ведь ссылка с классом даже

**Comment by arkhannanov** [comment]
Привет, Сергей сказал сделать в рамках ишью #2 (Там где он 4-ре пункта расписал, пункт 1-ый)

**Comment by Frolikow** [comment]
Ну так а почему не сделал то??
https://github.com/arkhannanov/FSD_CV/blob/49dd07fc9f1ba6799260dd30566ebb8a2f2e1755/src/blocks/contact/contact.scss#L45-L48

**Comment by arkhannanov** [comment]
Привет, ой я думал имелось ввиду это a.contact__item-content(href=`mailto: ${email}`)= email (задание класса через точку, а не в скобках).

**Comment by arkhannanov** [comment]
Готово)
